# Generated by Django 4.2.9 on 2024-01-08 14:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('encrypted_password', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_TFA_activated', models.BooleanField(default=False, verbose_name='Two Factor Authentication activated')),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[("don't_specify", "Don't Specify"), ('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them'), ('other', 'Other')], default="don't_specify", max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accounts/profile/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='accounts/thumb/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ('-date_joined',),
            },
        ),
    ]
