# Generated by Django 4.2.9 on 2024-01-08 14:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_TFA_activated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='accounts/id-proof'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('ui_ux_designer', 'Ui Ux Designer'), ('graphic_designer', 'Graphic Designer'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('quality_analyst', 'Quality Analyst')], default='project_manager', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('he/him', 'He/Him'), ('she/her', 'She/Her'), ('other', 'Other')], default='he/him', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
